# Site settings
name: Plataforma [Design]
title: Plataforma [Design]
email: rafael@webgoalcom.br
description: "Base de conteúdo para a equipe de Desin da Plataforma da Webgoal."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalinks: pretty
